name: Release
"on":
  push:
    branches:
      - main
      - next
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT }}
          NPM_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
